version: '3.8'
services:
  development_database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=newsfindme
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - "9000:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    command: command

volumes:
  db-data:
    driver: local  
    